version: '3.8'

services:
  app: 
    build:
      context: .
      target: production
    container_name: "wordle-app"
    volumes:
      - ./badger_db:/badger_db
    ports:
      - "9000:9000"
    environment:
      - POSTGRES_URL=postgresql://postgres:postgres@db:5432/wordle?sslmode=disable
      - PORT=9000
      - PASETO_KEY=12345678901234567890123456789012
      - BADGER_PATH=./badger_db
    healthcheck:
      test: ["CMD", "curl", "http://localhost:9000/health"]
      interval: 10s
      timeout: 30s
      retries: 5
    depends_on:
      db: 
        condition: service_healthy
    
  db:
    container_name: "wordle-db" 
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wordle
    ports:
      - "5432:5432"
    volumes:
        - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "wordle"]
      interval: 10s
      timeout: 30s
      retries: 5

  db-migrate:
    image: dekuyo/migrate-go:latest
    volumes:
      - ./repository/postgres/migrations:/migrations
    command: [ "-dir", "/migrations", "-dsn", "postgres://postgres:postgres@db:5432/wordle?sslmode=disable" ]  
    depends_on:
      db: 
        condition: service_healthy
      
    
volumes:
  db:
