version: '3.8'

services:
  app: 
    image: dekuyo/wordle-server:1.0.0
    volumes:
      - ./badger_db:/badger_db
    ports:
      - "9080:9080"
    environment:
      - POSTGRES_URL=postgresql://postgres:postgres@db:5432/wordle?sslmode=disable
      - PASETO_KEY=12345678901234567890123456789012
      - BADGER_PATH=/badger_db
      - PORT=9080

volumes:
  db: